INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME)
VALUES ('Kathy', 'Sierra'),
       ('Joshua', 'Bloch'),
       ('Robert C.', 'Martin'),
       ('Brian', 'Goetz'),
       ('Herbert', 'Schildt'),
       ('Scott', 'Meyers'),
       ('Joshua', 'Bloch'),
       ('Bruce', 'Eckel'),
       ('Maurice', 'Naftalin'),
       ('Raoul-Gabriel', 'Urma'),
       ('Joshua', 'Bloch'),
       ('Harold', 'O Reilly'),
       ('Erich', 'Gamma'),
       ('Paul', 'Deitel'),
       ('Gail', 'Anderson'),
       ('Marty', 'Hall'),
       ('Joel', 'Murach'),
       ('Stephen', 'Chin'),
       ('Sander', 'Mak'),
       ('Wallace', 'Jackson');