INSERT INTO BOOK (TITLE, PUBLISHER_ID)
VALUES ('Head First Java', 1),
       ('Effective Java', 2),
       ('Clean Code: A Handbook of Agile Software Craftsmanship', 3),
       ('Java Concurrency in Practice', 4),
       ('Java: The Complete Reference', 5),
       ('Java Performance: The Definitive Guide', 6),
       ('Java Cookbook', 7),
       ('Thinking in Java', 8),
       ('Java Generics and Collections', 9),
       ('Java 8 in Action', 10),
       ('Java Puzzlers: Traps, Pitfalls, and Corner Cases', 11),
       ('Java Network Programming', 12),
       ('Java Enterprise in a Nutshell', 13),
       ('Java Design Patterns: A Hands-On Experience with Real-World Examples', 14),
       ('Java How to Program', 15),
       ('JavaFX: Developing Rich Internet Applications', 16),
       ('JavaFX 8: Introduction by Example', 17),
       ('Java Servlet & JSP Cookbook', 18),
       ('Java 9 Modularity: Patterns and Practices for Developing Maintainable Applications', 19),
       ('JavaFX Essentials', 20);