INSERT INTO PUBLISHER (NAME)
VALUES ('Publisher 2'),
       ('Publisher 3'),
       ('Publisher 5'),
       ('Publisher 7'),
       ('Publisher 11'),
       ('Publisher 13'),
       ('Publisher 17'),
       ('Publisher 19'),
       ('Publisher 23'),
       ('Publisher 29'),
       ('Publisher 31'),
       ('Publisher 37'),
       ('Publisher 41'),
       ('Publisher 43'),
       ('Publisher 47'),
       ('Publisher 53'),
       ('Publisher 59'),
       ('Publisher 61'),
       ('Publisher 67'),
       ('Publisher 71');